const ActionType = {
    ADMIN: "ADMIN",
    ALL_USER:"ALL_USER",
    PRODUCTS:"PRODUCTS",
    ORDERS: "ORDERS",
    EDITPRODUCT:"EDITPRODUCT",
    SHOWORDERDETAILS : "SHOWORDERDETAILS",
    ORDERDELIVERED : "ORDERDELIVERED",
    SELLER : "SELLER",
    EDIT_SELLER:"EDIT_SELLER",
    CATEGORY:"CATEGORY",
    SUB_CATEGORY:"SUB_CATEGORY",
    LEFTBAR_TOGGLE:"LEFTBAR_TOGGLE",
    ADMIN_USER:"ADMIN_USER",
    EDIT_CATEGORY:"EDIT_CATEGORY",
    EDIT_OR_ADD :"EDIT_OR_ADD"
}

export default ActionType;